[package]
name = "metroidvainia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_ecs = "0.13.0"
bevy_rapier2d = {version = "*", features  = ["debug-render-2d"]}

leafwing-input-manager = { version = "0.13.2", features = ["egui"] }
bevy_egui = "0.25.0"
itertools = "0.13.0"
bevy_framepace = { version = "0.16.0", features = [] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
